version: '2.2'

services:
  banco:
    image: medq_db
    hostname: banco_de_dados
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 21751471
      bind-address: 0.0.0.0

  webapi:
    image: medq_api
    hostname: medq_api
    build: 
      context: .
      dockerfile: MedQ.API/Dockerfile
    expose:
      - 81
    ports:
      - "5001:81"
    environment:
      connectionString: "Server=banco_de_dados;Port=3306;Database=medq;Uid=root;Pwd=21751471"
      bind-address: 0.0.0.0

